apiVersion: apps/v1
kind: Deployment 
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: rj425/kub-demo-frontend:latest
          env:
            - name: AUTH_ADDRESS
              value: "auth-service.default.svc.cluster.local"
          resources: {}
