apiVersion: apps/v1
kind: Deployment 
metadata:
  name: tasks-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasks
  template:
    metadata:
      labels:
        app: tasks
    spec:
      containers:
        - name: tasks
          image: rj425/kub-demo-tasks:latest
          env:
            - name: AUTH_ADDRESS
              value: "auth-service.default.svc.cluster.local"
            - name: TASKS_FOLDER
              value: tasks
          resources: {}
